### ISSUE TITLE
Shifting contributors images in new heading "Contributors" 

### ISSUE THREAD

**Issue by snehafarkya** [mfranzon/mojo-is-awesome#15]
Hey @mfranzon, we can make the Readme file more attractive and systematic by adding a new heading **Contributors**.  I can shift images under this and add contributing guidelines.

Assign this issue to me under **hacktoberfest**  label

**Comment by mfranzon** [comment]
Good idea!
Thank you for contributing!

**Comment by mfranzon** [comment]
Close with #16
