### ISSUE TITLE
Missing Sections in Contributing.md

### ISSUE THREAD

**Issue by Mikerniker** [mfranzon/mojo-is-awesome#20]
Hello @mfranzon, just wanted to let you know that the links to some sections in the  [CONTRIBUTING.md](https://github.com/mfranzon/mojo-is-awesome/blob/main/CONTRIBUTING.md) file -- specifically in the Table of Contents don't seem to work because the sections are not available:  
![missingsectionsmojo](https://github.com/mfranzon/mojo-is-awesome/assets/63586831/55d7c571-d21c-45c1-b480-dc34eb9f9c6c)

This missing sections are:
- Your First Code Contribution
- Improving The Documentation
- Styleguides
- Commit Messages
- Join The Project Team

Adding these sections would be helpful for contributors. Thank you!

**Comment by mfranzon** [comment]
Thank you for pointing me out this bug!

**Comment by Mikerniker** [comment]
Hi @mfranzon, if you like I can fix the section for "Your First Code Contribution"
by copying over your instructions from the "Contributing" section in your [README.md](https://github.com/mfranzon/mojo-is-awesome#contributing) and I can also add a bit more details for this section. 

(As for the other sections on: 
Improving The Documentation, Styleguides, Commit Messages, Join The Project Team ) The [generator](https://github.com/bttger/contributing-gen) that created your [CONTRIBUTION.md](https://github.com/mfranzon/mojo-is-awesome/blob/main/CONTRIBUTING.md#attribution) seems to auto-generate these as empty sections, I'm not sure if you have a preference for the content here or if you would like me to remove any of them.

Let me know if you would like me to add the "Your First Contribution" section to the [CONTRIBUTING.md](https://github.com/mfranzon/mojo-is-awesome/blob/main/CONTRIBUTING.md#contributing-to-mojo-is-awesome). I can send a PR for this section, if you like. Thank you!

**Comment by mfranzon** [comment]
Sure! If you can open a PR that fixes this, it should be great!
Thank you!

**Comment by Mikerniker** [comment]
Ok, thank you @mfranzon , sent the PR for this!

**Comment by mfranzon** [comment]
Thank you @Mikerniker !
Close with #22
