### ISSUE TITLE
Adding icons in Readme headings

### ISSUE THREAD

**Issue by snehafarkya** [mfranzon/mojo-is-awesome#8]
Hi @mfranzon, let's make the **Readme file attractive** by adding some emojis. 
I would love to do that. Kindly assign this to me under **hacktoberfest**
Just like this: 
![image](https://github.com/mfranzon/mojo-is-awesome/assets/63949465/b8d01471-9ffc-427a-901b-83be3258966f)

Thankyou and have a nice day!

**Comment by mfranzon** [comment]
Great idea!

**Comment by mfranzon** [comment]
Close with #9
